# Generated by Django 4.1.5 on 2023-03-14 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_manage_delete_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manage',
            name='remark',
        ),
        migrations.AlterField(
            model_name='manage',
            name='id',
            field=models.IntegerField(blank=True, primary_key=True, serialize=False),
        ),
    ]
