# Generated by Django 4.1.5 on 2023-03-15 06:44

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_manage_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manage',
            name='text',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
