# Generated by Django 4.1.5 on 2023-03-15 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_manage_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manage',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
