# Generated by Django 4.1.5 on 2023-03-17 09:42

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_alter_image_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manage',
            name='text',
            field=ckeditor.fields.RichTextField(max_length=3000),
        ),
    ]
