# Generated by Django 4.1.5 on 2023-03-17 11:45

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_alter_manage_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', ckeditor.fields.RichTextField(max_length=3000)),
            ],
        ),
    ]
