# Generated by Django 4.1.5 on 2023-03-18 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_chick_peanut_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('Email', models.EmailField(max_length=50)),
                ('Message', models.TextField(max_length=100)),
            ],
        ),
    ]
