# Generated by Django 4.1.5 on 2023-03-20 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_chicki_peanuti'),
    ]

    operations = [
        migrations.AddField(
            model_name='chick',
            name='Title',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='image',
            name='Title',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='peanuti',
            name='Title',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
