# Generated by Django 4.1.5 on 2023-03-20 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_chick_title_image_title_peanuti_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chick',
            name='Title',
        ),
        migrations.AddField(
            model_name='chicki',
            name='Title',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
