# Generated by Django 4.1.5 on 2023-03-22 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_manage_title_manage_image_alter_manage_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutt',
            name='Title',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aboutt',
            name='image',
            field=models.ImageField(null=True, upload_to='img/'),
        ),
        migrations.AlterField(
            model_name='aboutt',
            name='text',
            field=models.CharField(max_length=10000),
        ),
    ]
