# Generated by Django 4.1.5 on 2023-03-22 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_aboutt_title_aboutt_image_alter_aboutt_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Title',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(null=True, upload_to='img/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='text',
            field=models.CharField(max_length=10000),
        ),
    ]
