# Generated by Django 4.1.5 on 2023-03-22 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_product_title_product_image_alter_product_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manage',
            name='image',
        ),
    ]
