# Generated by Django 4.1.5 on 2023-03-22 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_remove_manage_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='image',
            new_name='images',
        ),
    ]
