# Generated by Django 4.1.5 on 2023-03-23 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_rename_image_image_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='abouti',
            name='Title',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
