# Generated by Django 4.1.5 on 2023-03-23 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0030_slider'),
    ]

    operations = [
        migrations.CreateModel(
            name='contactI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='img/')),
                ('Title', models.CharField(max_length=100)),
            ],
        ),
    ]
