# Generated by Django 4.1.5 on 2023-03-23 12:00

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0031_contacti'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manage',
            name='text',
            field=ckeditor.fields.RichTextField(max_length=10000),
        ),
    ]
