# Generated by Django 4.1.5 on 2023-03-26 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0035_remove_contact_name_contact_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='phone',
            new_name='Phone',
        ),
    ]
