# Generated by Django 4.1.5 on 2023-03-26 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0036_rename_phone_contact_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='Message',
            new_name='Address',
        ),
    ]
